// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANEKFnFJojW-cVthJRRPi9hMumzcODH8g',
    appId: '1:484788321975:android:e02b2544cbb1b1a67ad732',
    messagingSenderId: '484788321975',
    projectId: 'gdg-phb',
    storageBucket: 'gdg-phb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Fn7mmqxuYpANj2Rq7u-SZqOL_8WTBXg',
    appId: '1:484788321975:ios:cb0ae73be3a2907f7ad732',
    messagingSenderId: '484788321975',
    projectId: 'gdg-phb',
    storageBucket: 'gdg-phb.appspot.com',
    iosClientId: '484788321975-dkp5e6ighim3cqes9th3l35obu3fr926.apps.googleusercontent.com',
    iosBundleId: 'com.example.cdgphbapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Fn7mmqxuYpANj2Rq7u-SZqOL_8WTBXg',
    appId: '1:484788321975:ios:5965f9c00bdd9d677ad732',
    messagingSenderId: '484788321975',
    projectId: 'gdg-phb',
    storageBucket: 'gdg-phb.appspot.com',
    iosClientId: '484788321975-3bq4k9u4cpkvlhjj494qh8dpm45alcgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.cdgphbapp.RunnerTests',
  );
}
