name: CICD

on:
  push:
    branches: ["develop"]

jobs:
  ci:
    name: Continuos Integration
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      
      - name: Download Android key
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: gdg-keystore.jks
          encodedString: ${{ secrets.KEY_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
      
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "11.x"
          cache: gradle
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: 'stable'
          cache: true
      
      - name: Delete depedencies
        run: flutter clean
        
      - name: Get Dependencies
        run: flutter pub get
        
      - name: Flutter tests
        run: flutter test
        
      - name: Flutter build
        run: flutter build apk --release
        
      - name: Upload Android APK 
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk
          
        
  cd: 
    name: Continuous Delivery
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get Android Build from artifacts
        uses: actions/download-artifact@v2
        with:
           name: android-release
      - name: Install firebase
        run: npm install firebase-tools -g 
      
      - name: Distribute app in firebase for testers
        run: |
          firebase appdistribution:distribute app-release.apk \
          --app "${{ secrets.FIREBASE_ANDROID_ID }}" \
          --release-notes "Hello GDG" \
          --groups "gdg-users" \
          --token "${{ secrets.FIREBASE_TOKEN }}"
      
       

      
      
      
        
      
      
      
      
